### ISSUE TITLE
Wrong coordinates in test

### ISSUE THREAD

**Issue by Nuzhny007** [blefaudeux/gmphd#1]
Hi!
In your test ( test_unit_GMPHD.cpp ) in function display it uses always only x coordinate:
**cvPoint(*tgt, *(tgt++))**
Here *tgt == *(tgt++).
It must be: cvPoint(*tgt, *(++tgt))

**Comment by blefaudeux** [comment]
indeed, sorry about that :/ This is pretty old code, tell me if you're interested, I could probably improve on it a fair bit if I find the time. Fixing that

**Comment by blefaudeux** [comment]
Should be fixed now, looks better indeed
